### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by buchs** [jfcarter2358/pipeline-reader#1]
Hi, I just `pip install`ed pipeline-reader on Windows 10. I found out that a dependency on cartils was missing and had to be separately installed.

**Comment by ptrsny** [comment]
+1

**Comment by jfcarter2358** [comment]
Apologies for taking so long to get to this, it got lost in the shuffle of the thousand other projects I've been working on. This should be resolved now with [this commit](https://github.com/jfcarter2358/pipeline-reader/commit/24bd1dc6a24bb23d6c508baf83e2940fe38e294f), let me know if you have any issues!

To get this fix in, install the latest release with `pipeline-reader==0.0.5`
